name: Update Progress Doc

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Update timestamp in docs/progress/PROGRESS.md
        run: |
          chmod +x scripts/update_progress.sh
          ./scripts/update_progress.sh
      - name: Commit changes if any
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/progress/PROGRESS.md
            git commit -m "chore: update progress timestamp"
            git push
          fi
